wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.7
    start_time: 1668123980.570692
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 5
      - 50
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.10.7
      5: 0.13.4
      8:
      - 4
      - 5
      10:
      - 5
    visualize:
      Program 1:
        panel_config:
          fieldSettings:
            value: n
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Program 1; n
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Program 1_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      Program 2:
        panel_config:
          fieldSettings:
            value: mu
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Program 2; mu
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Program 2_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
    viz:
      Program 3; heatmap:
        historyFieldSettings:
          key: Program 3; heatmap
          x-axis: _step
        id: wandb/heatmap/v1
